{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "/home/am-rutherford/repos/pymarl/src",
    "dependencies": [
      "munch==2.5.1.dev12",
      "numpy==1.20.3",
      "PyYAML==6.0",
      "sacred==0.7.2",
      "torch==1.10.2"
    ],
    "mainfile": "main.py",
    "name": "pymarl",
    "repositories": [],
    "sources": [
      [
        "main.py",
        "_sources/main_0c58e2e5c68e17bd852bcf41bf50c6fe.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/am-rutherford/anaconda3/envs/pymarl/lib/python3.7/site-packages/sacred-0.7.2-py3.7.egg/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"src/main.py\", line 38, in my_main\n    run(_run, config, _log)\n",
    "  File \"/home/am-rutherford/repos/pymarl/src/run.py\", line 49, in run\n    run_sequential(args=args, logger=logger)\n",
    "  File \"/home/am-rutherford/repos/pymarl/src/run.py\", line 179, in run_sequential\n    buffer.insert_episode_batch(episode_batch)\n",
    "  File \"/home/am-rutherford/repos/pymarl/src/components/per_buffer.py\", line 69, in insert_episode_batch\n    reward = th.sum(ep_batch[\"reward\"], device=self.device)\n",
    "TypeError: sum() received an invalid combination of arguments - got (Tensor, device=str), but expected one of:\n * (Tensor input, *, torch.dtype dtype)\n * (Tensor input, tuple of ints dim, bool keepdim, *, torch.dtype dtype, Tensor out)\n * (Tensor input, tuple of names dim, bool keepdim, *, torch.dtype dtype, Tensor out)\n\n"
  ],
  "heartbeat": "2022-04-01T18:04:50.707124",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz",
    "gpus": {
      "driver_version": "510.54",
      "gpus": [
        {
          "model": "NVIDIA GeForce GTX 1070",
          "persistence_mode": false,
          "total_memory": 8192
        }
      ]
    },
    "hostname": "fortinbras",
    "os": [
      "Linux",
      "Linux-5.4.0-105-generic-x86_64-with-debian-bullseye-sid"
    ],
    "python_version": "3.7.11"
  },
  "meta": {
    "command": "my_main",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2022-04-01T18:04:49.062446",
  "status": "FAILED",
  "stop_time": "2022-04-01T18:04:50.708465"
}